### ISSUE TITLE
How to access mysql directly?

### ISSUE THREAD

**Issue by w0lfcat** [webpwnized/mutillidae-docker#2]
I notice that mysql 3306/tcp is not listening when I bring up mutillidae via `docker-compose up` command

```
$ ss -ant
State    Recv-Q Send-Q  Local Address:Port Peer Address:Port
LISTEN   0      4096      127.0.0.1:443       127.0.0.1:*     
LISTEN   0      4096      127.0.0.1:80        127.0.0.1:*     
LISTEN   0      4096      127.0.0.1:81        127.0.0.1:*     
LISTEN   0      4096      127.0.0.1:82        127.0.0.1:* 
```

```
$ docker ps

IMAGE                                  PORTS                                        NAMES
webpwnized/mutillidae:database_admin   127.0.0.1:81->80/tcp                         mutillidae-docker_database_admin_1
webpwnized/mutillidae:www              127.0.0.1:80->80/tcp, 127.0.0.1:443->443/tcp mutillidae-docker_www_1
webpwnized/mutillidae:ldap_admin       443/tcp, 127.0.0.1:82->80/tcp                mutillidae-docker_directory_admin_1
webpwnized/mutillidae:database         3306/tcp, 33060/tcp                          mutillidae-docker_database_1
webpwnized/mutillidae:ldap             389/tcp, 636/tcp                             mutillidae-docker_directory_1

```
I also notice that it's not in `docker-compose.yml` file

Is there a way to access mysql database via command line instead of phpMyAdmin on port 81/tcp?

**Comment by webpwnized** [comment]
Sure. In the docker-compose.yml, map a port on your local machine to that same port on the MySQL server. You can add the following section to the "database" configuration to map container port 3306 over to your localhost port 3306.

```
    ports:
    - 127.0.0.1:3306:3306
```
   
I think it would look like this when complete:

```
  database:
    image: webpwnized/mutillidae:database
    build: 
        context: ./database
        dockerfile: Dockerfile
    **ports:
    - 127.0.0.1:3306:3306**
    networks:
      - datanet 
```
